---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: add key for docker
    apt_key: url="https://download.docker.com/linux/ubuntu/gpg"

  - name: add repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu (lsb_release -cs) stable
#    command: sudo add-apt-repository "deb [arch=amd64] 
#https://download.docker.com/linux/ubuntu (lsb_release -cs) stable"

#  - name: update package
#    apt:
#     update_cache: yes
  - name: install docker
    command: sudo apt-get install docker

